language: cpp

compiler:
  - clang
  - gcc

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

install: source ci/install.sh

script: bash ci/test.sh
