# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phxlk/Workspace/Computing/swatch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phxlk/Workspace/Computing/swatch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phxlk/Workspace/Computing/swatch/CMakeFiles /home/phxlk/Workspace/Computing/swatch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phxlk/Workspace/Computing/swatch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named swatch_impl

# Build rule for target.
swatch_impl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swatch_impl
.PHONY : swatch_impl

# fast build rule for target.
swatch_impl/fast:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/build
.PHONY : swatch_impl/fast

#=============================================================================
# Target rules for targets named swatch_test

# Build rule for target.
swatch_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swatch_test
.PHONY : swatch_test

# fast build rule for target.
swatch_test/fast:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/build
.PHONY : swatch_test/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f ext/gtest/CMakeFiles/googletest.dir/build.make ext/gtest/CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named uhal

# Build rule for target.
uhal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uhal
.PHONY : uhal

# fast build rule for target.
uhal/fast:
	$(MAKE) -f ext/uhal/CMakeFiles/uhal.dir/build.make ext/uhal/CMakeFiles/uhal.dir/build
.PHONY : uhal/fast

src/board/Board.o: src/board/Board.cpp.o
.PHONY : src/board/Board.o

# target to build an object file
src/board/Board.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/Board.cpp.o
.PHONY : src/board/Board.cpp.o

src/board/Board.i: src/board/Board.cpp.i
.PHONY : src/board/Board.i

# target to preprocess a source file
src/board/Board.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/Board.cpp.i
.PHONY : src/board/Board.cpp.i

src/board/Board.s: src/board/Board.cpp.s
.PHONY : src/board/Board.s

# target to generate assembly for a file
src/board/Board.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/Board.cpp.s
.PHONY : src/board/Board.cpp.s

src/board/BoardFactory.o: src/board/BoardFactory.cpp.o
.PHONY : src/board/BoardFactory.o

# target to build an object file
src/board/BoardFactory.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/BoardFactory.cpp.o
.PHONY : src/board/BoardFactory.cpp.o

src/board/BoardFactory.i: src/board/BoardFactory.cpp.i
.PHONY : src/board/BoardFactory.i

# target to preprocess a source file
src/board/BoardFactory.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/BoardFactory.cpp.i
.PHONY : src/board/BoardFactory.cpp.i

src/board/BoardFactory.s: src/board/BoardFactory.cpp.s
.PHONY : src/board/BoardFactory.s

# target to generate assembly for a file
src/board/BoardFactory.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/BoardFactory.cpp.s
.PHONY : src/board/BoardFactory.cpp.s

src/board/CTP7Board.o: src/board/CTP7Board.cpp.o
.PHONY : src/board/CTP7Board.o

# target to build an object file
src/board/CTP7Board.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/CTP7Board.cpp.o
.PHONY : src/board/CTP7Board.cpp.o

src/board/CTP7Board.i: src/board/CTP7Board.cpp.i
.PHONY : src/board/CTP7Board.i

# target to preprocess a source file
src/board/CTP7Board.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/CTP7Board.cpp.i
.PHONY : src/board/CTP7Board.cpp.i

src/board/CTP7Board.s: src/board/CTP7Board.cpp.s
.PHONY : src/board/CTP7Board.s

# target to generate assembly for a file
src/board/CTP7Board.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/CTP7Board.cpp.s
.PHONY : src/board/CTP7Board.cpp.s

src/board/MP7Board.o: src/board/MP7Board.cpp.o
.PHONY : src/board/MP7Board.o

# target to build an object file
src/board/MP7Board.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/MP7Board.cpp.o
.PHONY : src/board/MP7Board.cpp.o

src/board/MP7Board.i: src/board/MP7Board.cpp.i
.PHONY : src/board/MP7Board.i

# target to preprocess a source file
src/board/MP7Board.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/MP7Board.cpp.i
.PHONY : src/board/MP7Board.cpp.i

src/board/MP7Board.s: src/board/MP7Board.cpp.s
.PHONY : src/board/MP7Board.s

# target to generate assembly for a file
src/board/MP7Board.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/MP7Board.cpp.s
.PHONY : src/board/MP7Board.cpp.s

src/board/MTF7Board.o: src/board/MTF7Board.cpp.o
.PHONY : src/board/MTF7Board.o

# target to build an object file
src/board/MTF7Board.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/MTF7Board.cpp.o
.PHONY : src/board/MTF7Board.cpp.o

src/board/MTF7Board.i: src/board/MTF7Board.cpp.i
.PHONY : src/board/MTF7Board.i

# target to preprocess a source file
src/board/MTF7Board.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/MTF7Board.cpp.i
.PHONY : src/board/MTF7Board.cpp.i

src/board/MTF7Board.s: src/board/MTF7Board.cpp.s
.PHONY : src/board/MTF7Board.s

# target to generate assembly for a file
src/board/MTF7Board.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/board/MTF7Board.cpp.s
.PHONY : src/board/MTF7Board.cpp.s

src/core/Device.o: src/core/Device.cpp.o
.PHONY : src/core/Device.o

# target to build an object file
src/core/Device.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Device.cpp.o
.PHONY : src/core/Device.cpp.o

src/core/Device.i: src/core/Device.cpp.i
.PHONY : src/core/Device.i

# target to preprocess a source file
src/core/Device.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Device.cpp.i
.PHONY : src/core/Device.cpp.i

src/core/Device.s: src/core/Device.cpp.s
.PHONY : src/core/Device.s

# target to generate assembly for a file
src/core/Device.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Device.cpp.s
.PHONY : src/core/Device.cpp.s

src/core/Link.o: src/core/Link.cpp.o
.PHONY : src/core/Link.o

# target to build an object file
src/core/Link.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Link.cpp.o
.PHONY : src/core/Link.cpp.o

src/core/Link.i: src/core/Link.cpp.i
.PHONY : src/core/Link.i

# target to preprocess a source file
src/core/Link.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Link.cpp.i
.PHONY : src/core/Link.cpp.i

src/core/Link.s: src/core/Link.cpp.s
.PHONY : src/core/Link.s

# target to generate assembly for a file
src/core/Link.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Link.cpp.s
.PHONY : src/core/Link.cpp.s

src/core/Port.o: src/core/Port.cpp.o
.PHONY : src/core/Port.o

# target to build an object file
src/core/Port.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Port.cpp.o
.PHONY : src/core/Port.cpp.o

src/core/Port.i: src/core/Port.cpp.i
.PHONY : src/core/Port.i

# target to preprocess a source file
src/core/Port.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Port.cpp.i
.PHONY : src/core/Port.cpp.i

src/core/Port.s: src/core/Port.cpp.s
.PHONY : src/core/Port.s

# target to generate assembly for a file
src/core/Port.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/Port.cpp.s
.PHONY : src/core/Port.cpp.s

src/core/exception.o: src/core/exception.cpp.o
.PHONY : src/core/exception.o

# target to build an object file
src/core/exception.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/exception.cpp.o
.PHONY : src/core/exception.cpp.o

src/core/exception.i: src/core/exception.cpp.i
.PHONY : src/core/exception.i

# target to preprocess a source file
src/core/exception.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/exception.cpp.i
.PHONY : src/core/exception.cpp.i

src/core/exception.s: src/core/exception.cpp.s
.PHONY : src/core/exception.s

# target to generate assembly for a file
src/core/exception.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_impl.dir/build.make CMakeFiles/swatch_impl.dir/src/core/exception.cpp.s
.PHONY : src/core/exception.cpp.s

test/DeviceTest.o: test/DeviceTest.cpp.o
.PHONY : test/DeviceTest.o

# target to build an object file
test/DeviceTest.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/test/DeviceTest.cpp.o
.PHONY : test/DeviceTest.cpp.o

test/DeviceTest.i: test/DeviceTest.cpp.i
.PHONY : test/DeviceTest.i

# target to preprocess a source file
test/DeviceTest.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/test/DeviceTest.cpp.i
.PHONY : test/DeviceTest.cpp.i

test/DeviceTest.s: test/DeviceTest.cpp.s
.PHONY : test/DeviceTest.s

# target to generate assembly for a file
test/DeviceTest.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/test/DeviceTest.cpp.s
.PHONY : test/DeviceTest.cpp.s

test/DummyTest.o: test/DummyTest.cpp.o
.PHONY : test/DummyTest.o

# target to build an object file
test/DummyTest.cpp.o:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/test/DummyTest.cpp.o
.PHONY : test/DummyTest.cpp.o

test/DummyTest.i: test/DummyTest.cpp.i
.PHONY : test/DummyTest.i

# target to preprocess a source file
test/DummyTest.cpp.i:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/test/DummyTest.cpp.i
.PHONY : test/DummyTest.cpp.i

test/DummyTest.s: test/DummyTest.cpp.s
.PHONY : test/DummyTest.s

# target to generate assembly for a file
test/DummyTest.cpp.s:
	$(MAKE) -f CMakeFiles/swatch_test.dir/build.make CMakeFiles/swatch_test.dir/test/DummyTest.cpp.s
.PHONY : test/DummyTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... swatch_impl"
	@echo "... swatch_test"
	@echo "... test"
	@echo "... googletest"
	@echo "... uhal"
	@echo "... src/board/Board.o"
	@echo "... src/board/Board.i"
	@echo "... src/board/Board.s"
	@echo "... src/board/BoardFactory.o"
	@echo "... src/board/BoardFactory.i"
	@echo "... src/board/BoardFactory.s"
	@echo "... src/board/CTP7Board.o"
	@echo "... src/board/CTP7Board.i"
	@echo "... src/board/CTP7Board.s"
	@echo "... src/board/MP7Board.o"
	@echo "... src/board/MP7Board.i"
	@echo "... src/board/MP7Board.s"
	@echo "... src/board/MTF7Board.o"
	@echo "... src/board/MTF7Board.i"
	@echo "... src/board/MTF7Board.s"
	@echo "... src/core/Device.o"
	@echo "... src/core/Device.i"
	@echo "... src/core/Device.s"
	@echo "... src/core/Link.o"
	@echo "... src/core/Link.i"
	@echo "... src/core/Link.s"
	@echo "... src/core/Port.o"
	@echo "... src/core/Port.i"
	@echo "... src/core/Port.s"
	@echo "... src/core/exception.o"
	@echo "... src/core/exception.i"
	@echo "... src/core/exception.s"
	@echo "... test/DeviceTest.o"
	@echo "... test/DeviceTest.i"
	@echo "... test/DeviceTest.s"
	@echo "... test/DummyTest.o"
	@echo "... test/DummyTest.i"
	@echo "... test/DummyTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

